version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "8080:80"